# Generated by Django 4.1.7 on 2023-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
