# Generated by Django 4.1.7 on 2023-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='memo',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
