# Generated by Django 4.1.7 on 2023-03-15 07:17

import common_utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(choices=[('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('xxxx', 'xxxx')], max_length=4, validators=[django.core.validators.RegexValidator(message='Not match MBTI Characters', regex='[IEx][SNx][TFx][PJx]')])),
                ('title', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'mbti_class',
            },
        ),
        migrations.CreateModel(
            name='MBTIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('energy', 'Energy'), ('information', 'Information'), ('decision', 'Decision'), ('lifestyle', 'Lifestyle')], max_length=20)),
                ('text', models.TextField()),
                ('select0_score', models.SmallIntegerField(verbose_name='Not at all')),
                ('select1_score', models.SmallIntegerField(verbose_name='No')),
                ('select2_score', models.SmallIntegerField(verbose_name='Yes')),
                ('select3_score', models.SmallIntegerField(verbose_name='Absolutely')),
            ],
            options={
                'db_table': 'mbti_question',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='MBTITestThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.PositiveSmallIntegerField()),
                ('information', models.PositiveSmallIntegerField()),
                ('decision', models.PositiveSmallIntegerField()),
                ('lifestyle', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'mbti_question_threshold',
            },
        ),
        migrations.CreateModel(
            name='MBTIClassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common_utils.path_and_rename)),
                ('name', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=255)),
                ('mbti_class_id', models.ForeignKey(db_column='mbti_class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mbti_class_image_set', to='mbti.mbticlass')),
            ],
            options={
                'db_table': 'mbti_class_image',
            },
        ),
        migrations.CreateModel(
            name='MBTIClassHashtagAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_id', models.ForeignKey(db_column='hashtag_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mbti_class_assoc_set', to='hashtag.hashtag')),
                ('mbti_class_id', models.ForeignKey(db_column='mbti_class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashtag_assoc_set', to='mbti.mbticlass')),
            ],
            options={
                'verbose_name': 'MBTI class hashtag',
                'db_table': 'mbti_class_hashtag',
            },
        ),
    ]
